# SARbayes/ISRID/settings.yaml

# Worksheet title
title: ISRID

# Use argument names.
# See: http://openpyxl.readthedocs.org/en/latest/styles.html
styles: 
    font: 
        name: Monospace
        size: 10

columns: 
    key: 
        index: 1
    city:
        index: 4
    county: 
        index: 5
    date: 
        index: 3
    lkp_ns: 
        index: 33
    lkp_ew: 
        index: 34
    temp_max: 
        index: 37
    temp_min: 
        index: 38
    wind_speed: 
        index: 39
    snow: 
        index: 41
    rain: 
        index: 42

# NOAA Tokens
tokens: 
  - CAKlHptoFxCtALqpfyjIKtmpfCbQIWse 
  - ZTZdegFESMPyfcbxZzdApotLPuZqZbjV
  - koceZQKoKxrRBnsKGKwkvVSXUUsrjUWO
  - tyatdcCMMaBwWKAHdQvQkVLxYcUbizCt
  - tZAjzLeMUjwHRzbyCshFDCUsUGecVpWT
  - XuynqsXFIGjQEXIshdoyFizBgrdZdwXO
  - kClxOskPZexpKAcoLJeipIAUvGBImaMI
  - uRUpbVmlsHiLWbcmaZotgGwoDZnkozeS
  - pLCcTVobSdphuEvXyOyhkAbVlObmWQra
  - FgFYQJXIFJwfhPAWbARqFNwPqdokgUeC
  - TZLkSchIioQEPMWNWcuakCCLUbvJaUhk
  - KEDFNJKicieREzQMlFFQlWsLGXISxqOP
  - xLCcTVopsdphuEvPyOyhkAbVlObmWQra
  - pWmAdZysIShKsPkxbGeKAjeutJYqpOus
  - sDDqnqqBmkfUFSEzXoElcgzmYrtTyZGz
  - kCbjzgsMEDpHugAFXbBkvHSQkdmqZMHj
